import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";

const montSans = localFont({
  src: "./fonts/Montserrat-Regular.ttf",
  variable: "--font-mont-sans",
  weight: "100 900",
});
const montMono = localFont({
  src: "./fonts/Montserrat-Regular.ttf",
  variable: "--font-mont-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Harsh Gupta Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montSans.variable} ${montMono.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
